# Copyright (c) Prometeo AI, Inc. All rights reserved. 


trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Add conda to PATH (Linux)

  - bash: |
      conda create -q -n pyenv python=$(python.version) -y
      conda env update -q -n pyenv -f conda.yaml
    displayName: 'Conda install dependencies'

  - bash: |
      source activate pyenv
      pytest tests --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()