# Copyright (c) Prometeo AI, Inc. All rights reserved. 
#
# To create the conda environment (codebase):
# $ conda env create -n prometeo_base -f conda.yaml
#
# To update the conda environment:
# $ conda env update -n prometeo_base -f conda.yaml
#
# To register the conda environment in Jupyter:
# $ python -m ipykernel install --user --name prometeo_base --display-name "Python (prometeo_base)"
#

channels:
- conda-forge
- defaults
dependencies:
- numpy>=1.16.0
- requests>=2.18.4
- beautifulsoup4>=4.6.0
- flask>=1.0.2
- cherrypy>=12.0.1
- paste>=2.0.3
- jupyter>=1.0.0
- pip:
  - pandas>=0.23.4
  - scikit-learn>=0.19.1
  - scipy>=0.19.0
  - matplotlib>=1.5.3
  - bokeh>=0.12.6
  - sqlalchemy>=1.2.4
  - xmlrunner>=1.7.7
  - coverage>=4.5.1
  - pytest>=3.6.3
  - papermill>=0.17.1
  - wget>=3.2
  - numexpr>=2.6.8
  - sphinx>=1.8.4
  - sphinx_rtd_theme>=0.4.3
